accounts/urls.py
from django.urls import include, path

from . import views

app_name = 'accounts'
urlpatterns = [
    # Додати URL авторизації за замовчуванням
    path('', include('django.contrib.auth.urls')),
    # Сторінка реєстрації
    path('register/', views.register, name='register'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Головна сторінка
    path('', views.index, name='index'),
    # Сторінка зі списком усіх тем
    path('topics/', views.topics, name='topics'),
    # Сторінка з інформацією за окремою темою
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Сторінка для додавання нової теми
    path('new_topic/', views.new_topic, name='new_topic'),
    # Сторінка для додавання нового допису
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Сторінка для редагування допису
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Topic(models.Model):
    """Тема, яку вивчає користувач"""

    text = models.CharField(max_length=255, verbose_name="Назва теми")
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="Створено")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Власник")

    class Meta:
        verbose_name = "Тема"
        verbose_name_plural = "Теми"

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Дописи за темами"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name="Тема")
    text = models.TextField(verbose_name="Текст")
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="Створено")

    class Meta:
        verbose_name = "Допис"
        verbose_name_plural = "Дописи"

    def __str__(self):
        return f"{self.text[:50]}..."
    

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render

# Create your views here.

def register(request):
    """Реєструє нового користувача"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    
    context = {'form': form}
    return render(request, 'accounts/register.html', context)

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render

from .forms import EntryForm, TopicForm
from .models import Entry, Topic

# Create your views here.

def index(request):
    """Головна сторінка застосунку"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Виводе список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Виводе одну тему і всі її дописи"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries,
    }
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Додає нову тему"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Додає новий допис до визначеної теми"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    
    context = {
        'topic': topic,
        'form': form,
    }
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редагує існуючий допис"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {
        'entry': entry,
        'topic': topic,
        'form': form
    }
    return render(request, 'learning_logs/edit_entry.html', context)

accounts/templates/accounts/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <form action="{% url 'accounts:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">Реєстрація</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Learning Log</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Журнал навчання</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button> 
        
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:topics' %}">Теми</a>
            </li> 
          </ul> 
          
          <ul class="navbar-nav ms-auto mb-2 mb-md-0">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <span class="navbar-text me-2">{{ user.username }}</span>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Вхід</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Реєстрація</a>
              </li>
            {% endif %}
          </ul>

          {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-secondary btn-sm">Вихід</button>
            </form>
          {% endif %}
        </div>
      </div>
    </nav>

    <main class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>

      <div>
        {% block content %}
        {% endblock %}
      </div>
    </main>

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h2>

  <h3>Редагування допису</h3>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти допис</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <h1 class="display-3">Журнал навчання</h1>
  </div>
  <p class="lead">
    Журнал навчання допомагає Вам відслідковувати ваші успіхи у вивченні будь-якої теми.
  </p>

  <a class="btn btn-primary btn-lg mt-1" href="{% url 'learning_logs:topics' %}">
    Список тем
  </a>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h2>

  <h3>Новий допис до теми</h3>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Новий допис</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>Нова тема</h2>

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Додати тему</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h2>Тема: {{ topic }}</h2>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Додати новий допис</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:"d.m.Y H:i" }}
        <small>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">Змінити допис</a>
        </small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>До теми ще не додано дописів.</p>
  {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h2>Теми</h2>
{% endblock page_header %}

{% block content %}
  <ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">Жодної теми ще не було додано.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">Додати нову тему</a>
{% endblock content %}